//-----------------------------------------------------------------------
// <copyright>
//		Created by Matt Weber <matt@badecho.com>
//		Copyright @ 2023 Bad Echo LLC. All rights reserved.
//
//		Bad Echo Technologies are licensed under the
//		GNU Affero General Public License v3.0.
//
//		See accompanying file LICENSE.md or a copy at:
//		https://www.gnu.org/licenses/agpl-3.0.html
// </copyright>
//-----------------------------------------------------------------------

namespace BadEcho.Vision.Apocalypse.Views;

/// <summary>
/// Provides a view for displaying an event generated by the Apocalypse system in an Omnified game.
/// </summary>
public partial class ApocalypseEventView
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ApocalypseEventView"/> class.
    /// </summary>
    public ApocalypseEventView() 
        => InitializeComponent();
}