//-----------------------------------------------------------------------
// <copyright>
//      Created by Matt Weber <matt@badecho.com>
//      Copyright @ 2022 Bad Echo LLC. All rights reserved.
//
//		Bad Echo Technologies are licensed under a
//		Creative Commons Attribution-NonCommercial 4.0 International License.
//
//		See accompanying file LICENSE.md or a copy at:
//		http://creativecommons.org/licenses/by-nc/4.0/
// </copyright>
//-----------------------------------------------------------------------

namespace BadEcho.Vision.Apocalypse.Views;

/// <summary>
/// Provides a view for displaying an event generated by the Apocalypse system in an Omnified game.
/// </summary>
public partial class ApocalypseEventView
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ApocalypseEventView"/> class.
    /// </summary>
    public ApocalypseEventView() 
        => InitializeComponent();
}