//-----------------------------------------------------------------------
// <copyright>
//      Created by Matt Weber <matt@badecho.com>
//      Copyright @ 2021 Bad Echo LLC. All rights reserved.
//
//		Bad Echo Technologies are licensed under a
//		Creative Commons Attribution-NonCommercial 4.0 International License.
//
//		See accompanying file LICENSE.md or a copy at:
//		http://creativecommons.org/licenses/by-nc/4.0/
// </copyright>
//-----------------------------------------------------------------------

namespace BadEcho.Omnified.Vision.Apocalypse
{
    /// <summary>
    /// Provides a description for the event generated by the Apocalypse system upon the player becoming cured
    /// of a Fatalis debuff they were previously inflicted with.
    /// </summary>
    public sealed class FatalisCuredEvent
    {
        /// <summary>
        /// Gets the number of times that the player died due their Fatalis affliction.
        /// </summary>
        public int Deaths
        { get; init; }
    }
}
