//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadEcho.Game.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadEcho.Game.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture atlas already has a region named &apos;{0}&apos;..
        /// </summary>
        internal static string AtlasAlreadyHasRegion {
            get {
                return ResourceManager.GetString("AtlasAlreadyHasRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex code string was not recognized as a valid Color..
        /// </summary>
        internal static string ColorBadHexString {
            get {
                return ResourceManager.GetString("ColorBadHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derived control class must pass itself as the generic self-recurring type parameter..
        /// </summary>
        internal static string ControlNotSelfRecurring {
            get {
                return ResourceManager.GetString("ControlNotSelfRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing expected effect resource &apos;{0}&apos;..
        /// </summary>
        internal static string EffectMissingResource {
            get {
                return ResourceManager.GetString("EffectMissingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified element is outside this quadtree&apos;s boundaries..
        /// </summary>
        internal static string ElementOutsideQuadtreeBounds {
            get {
                return ResourceManager.GetString("ElementOutsideQuadtreeBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified column is outside the range of this grid&apos;s columns..
        /// </summary>
        internal static string GridColumnOutOfRange {
            get {
                return ResourceManager.GetString("GridColumnOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified row is outside the range of this grid&apos;s rows..
        /// </summary>
        internal static string GridRowOutOfRange {
            get {
                return ResourceManager.GetString("GridRowOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index data has already been primed for loading into an index buffer and can no longer be added to..
        /// </summary>
        internal static string IndexDataAlreadyLoaded {
            get {
                return ResourceManager.GetString("IndexDataAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid movement direction for camera dead zone..
        /// </summary>
        internal static string InvalidDeadZoneDirection {
            get {
                return ResourceManager.GetString("InvalidDeadZoneDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label control requires a font to be set in order to draw text..
        /// </summary>
        internal static string LabelNoFont {
            get {
                return ResourceManager.GetString("LabelNoFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount of zoom must be greater than zero..
        /// </summary>
        internal static string MaximumZoomCannotBeZeroOrLess {
            get {
                return ResourceManager.GetString("MaximumZoomCannotBeZeroOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum amount of zoom must be greater than zero..
        /// </summary>
        internal static string MinimumZoomCannotBeZeroOrLess {
            get {
                return ResourceManager.GetString("MinimumZoomCannotBeZeroOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No indices were provided for the vertex data..
        /// </summary>
        internal static string ModelNoVertexIndices {
            get {
                return ResourceManager.GetString("ModelNoVertexIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity has been associated with this collider..
        /// </summary>
        internal static string NoEntityAssociated {
            get {
                return ResourceManager.GetString("NoEntityAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control cannot process input without an input handler..
        /// </summary>
        internal static string NoInputHandler {
            get {
                return ResourceManager.GetString("NoInputHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite sheet already has an animation with the specified name..
        /// </summary>
        internal static string SheetAlreadyHasAnimation {
            get {
                return ResourceManager.GetString("SheetAlreadyHasAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite sheet contains no frames for the specified animation..
        /// </summary>
        internal static string SheetNoFramesForAnimation {
            get {
                return ResourceManager.GetString("SheetNoFramesForAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setter expression targets a property not belonging to the control type being styled..
        /// </summary>
        internal static string StyleSetterNonLocalProperty {
            get {
                return ResourceManager.GetString("StyleSetterNonLocalProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setter expression for style can only target properties and no other member types..
        /// </summary>
        internal static string StyleSetterNonPropertyAccess {
            get {
                return ResourceManager.GetString("StyleSetterNonPropertyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setter expression for style must access a control&apos;s property..
        /// </summary>
        internal static string StyleSetterNotMemberAccess {
            get {
                return ResourceManager.GetString("StyleSetterNotMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile set is not based on a single image and the specified tile lacks a texture..
        /// </summary>
        internal static string TileHasNoTexture {
            get {
                return ResourceManager.GetString("TileHasNoTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tile with the same ID of &apos;{0}&apos; already exists in this tile set..
        /// </summary>
        internal static string TileSetAlreadyHasTile {
            get {
                return ResourceManager.GetString("TileSetAlreadyHasTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configured data for the specified tile could be found..
        /// </summary>
        internal static string TileSetMissingTile {
            get {
                return ResourceManager.GetString("TileSetMissingTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics device has not been initialized yet..
        /// </summary>
        internal static string UninitializedGraphicsDevice {
            get {
                return ResourceManager.GetString("UninitializedGraphicsDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex data has already been primed for loading into a vertex buffer and can no longer be added to..
        /// </summary>
        internal static string VertexDataAlreadyLoaded {
            get {
                return ResourceManager.GetString("VertexDataAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom speed cannot be negative..
        /// </summary>
        internal static string ZoomSpeedCannotBeNegative {
            get {
                return ResourceManager.GetString("ZoomSpeedCannotBeNegative", resourceCulture);
            }
        }
    }
}
