//-----------------------------------------------------------------------
// <copyright>
//		Created by Matt Weber <matt@badecho.com>
//		Copyright @ 2023 Bad Echo LLC. All rights reserved.
//
//		Bad Echo Technologies are licensed under the
//		GNU Affero General Public License v3.0.
//
//		See accompanying file LICENSE.md or a copy at:
//		https://www.gnu.org/licenses/agpl-3.0.html
// </copyright>
//-----------------------------------------------------------------------

namespace BadEcho.Vision.Apocalypse.ViewModels;

/// <summary>
/// Defines a view model that facilitates the display of an event generated by the Player Apocalypse subsystem in
/// an Omnified game.
/// </summary>
public interface IPlayerApocalypseEventViewModel : IApocalypseEventViewModel
{
    /// <summary>
    /// Gets or sets the primary die roll for the bound Player Apocalypse event.
    /// </summary>
    int DieRoll { get; set; }
}