//-----------------------------------------------------------------------
// <copyright>
//      Created by Matt Weber <matt@badecho.com>
//      Copyright @ 2021 Bad Echo LLC. All rights reserved.
//
//		Bad Echo Technologies are licensed under a
//		Creative Commons Attribution-NonCommercial 4.0 International License.
//
//		See accompanying file LICENSE.md or a copy at:
//		http://creativecommons.org/licenses/by-nc/4.0/
// </copyright>
//-----------------------------------------------------------------------

namespace BadEcho.Omnified.Vision.Apocalypse.ViewModels;

/// <summary>
/// Defines a view model that facilitates the display of an event generated by the Player Apocalypse subsystem in
/// an Omnified game.
/// </summary>
public interface IPlayerApocalypseEventViewModel : IApocalypseEventViewModel
{
    /// <summary>
    /// Gets or sets the primary die roll for the bound Player Apocalypse event.
    /// </summary>
    int DieRoll { get; set; }
}