//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadEcho.Extensibility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadEcho.Extensibility.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plugin directory was explicitly specified in this application&apos;s configuration, however &apos;{0}&apos; does not exist. Please ensure that a desired plugin directory exists when configuring its use, or simply forego specifying an explicit plugin directory name if its existence cannot be guaranteed..
        /// </summary>
        internal static string ExtensibilityConfigurationDirectoryNotFound {
            get {
                return ResourceManager.GetString("ExtensibilityConfigurationDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot check if assembly &apos;{0}&apos; is an extensibility point because it is missing the following dependency: &apos;{1}&apos;.
        /// </summary>
        internal static string ExtensibilityPointMissingDependency {
            get {
                return ResourceManager.GetString("ExtensibilityPointMissingDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a registered filterable family identity value. Registration of a filterable family requires a FilterableFamily export action..
        /// </summary>
        internal static string FamilyIdNotRegistered {
            get {
                return ResourceManager.GetString("FamilyIdNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid filterable family identity value. Values must be parseable as standard globally unique identifiers..
        /// </summary>
        internal static string FamilyIdNotValid {
            get {
                return ResourceManager.GetString("FamilyIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No routable plugin has been registered to handle calls made to &apos;{0}&apos;..
        /// </summary>
        internal static string HostAdapterUnregisteredMethod {
            get {
                return ResourceManager.GetString("HostAdapterUnregisteredMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection of exported parts into an attributed pluggable part of type &apos;{0}&apos; within a self-armed context requires said part to be assignable to the specified dependency value of type &apos;{1}&apos;..
        /// </summary>
        internal static string IncompatibleDependencyTypeForInjection {
            get {
                return ResourceManager.GetString("IncompatibleDependencyTypeForInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple exports for contract type &apos;{0}&apos; belong to the &apos;{1}&apos; filterable family; any part beyond the first of its type from a filterable context is ignored..
        /// </summary>
        internal static string MultipleExportsFoundForFamily {
            get {
                return ResourceManager.GetString("MultipleExportsFoundForFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple exports for the locally exported contract type &apos;{0}&apos; were found. Only a single provider should ever be available for contract types meant to be loaded from a local context..
        /// </summary>
        internal static string MultipleExportsFoundForLocalContract {
            get {
                return ResourceManager.GetString("MultipleExportsFoundForLocalContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensibility configuration lacks registration for contract &apos;{0}&apos;..
        /// </summary>
        internal static string NoContractInConfiguration {
            get {
                return ResourceManager.GetString("NoContractInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry was not armed with an expected dependency..
        /// </summary>
        internal static string NoDependencyArmed {
            get {
                return ResourceManager.GetString("NoDependencyArmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No export for contract type &apos;{0}&apos; belongs to the &apos;{1}&apos; filterable family..
        /// </summary>
        internal static string NoExportFoundForFamily {
            get {
                return ResourceManager.GetString("NoExportFoundForFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No local export for the contract type &apos;{0}&apos; was found. If this is an expected contract, then it should be exported within the consuming component&apos;s own assembly. If expectancy is tenuous, check for support via the appropriate methods provided by the plugin host system first..
        /// </summary>
        internal static string NoExportFoundForLocalContract {
            get {
                return ResourceManager.GetString("NoExportFoundForLocalContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; being scanned for pluggable exports failed to load due to most likely not being a valid .NET assembly..
        /// </summary>
        internal static string PluginBadImageException {
            get {
                return ResourceManager.GetString("PluginBadImageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; being scanned for pluggable exports failed to load..
        /// </summary>
        internal static string PluginFileLoadException {
            get {
                return ResourceManager.GetString("PluginFileLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executing process is unmanaged; therefore, no contract implementation is able to be exported by it..
        /// </summary>
        internal static string ProcessCannotExportContracts {
            get {
                return ResourceManager.GetString("ProcessCannotExportContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid call-routable plugin identity value. Values must be parseable as standard globally unique identifiers..
        /// </summary>
        internal static string RoutablePluginIdNotValid {
            get {
                return ResourceManager.GetString("RoutablePluginIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoutableProxy was not provided a IHostAdapter due to improper initialization. Use a static factory method such as RoutableProxy.Create instead to initialize the proxy properly..
        /// </summary>
        internal static string RoutableProxyNotInitializedCorrectly {
            get {
                return ResourceManager.GetString("RoutableProxyNotInitializedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteProxy instance was somehow invoked with null method information..
        /// </summary>
        internal static string RoutableProxyNullMethodInfo {
            get {
                return ResourceManager.GetString("RoutableProxyNullMethodInfo", resourceCulture);
            }
        }
    }
}
