//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadEcho.Omnified.Vision.Apocalypse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EffectMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EffectMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadEcho.Omnified.Vision.Apocalypse.Properties.EffectMessages", typeof(EffectMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy has been critically hit ({0}) causing an additional {1} damage!.
        /// </summary>
        public static string CriticalHit {
            get {
                return ResourceManager.GetString("CriticalHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra damage ({0}x).
        /// </summary>
        public static string ExtraDamage {
            get {
                return ResourceManager.GetString("ExtraDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, the player has been stricken with Fatalis for an unknown period of time....
        /// </summary>
        public static string Fatalis {
            get {
                return ResourceManager.GetString("Fatalis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miraculously, after suffering with it for {0} minutes and dying {1} times, the player has been cured of Fatalis!.
        /// </summary>
        public static string FatalisCured {
            get {
                return ResourceManager.GetString("FatalisCured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player, afflicted with Fatalis, dies immediately from the enemy attack, losing all {0} points of their health..
        /// </summary>
        public static string FatalisDeath {
            get {
                return ResourceManager.GetString("FatalisDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player has unlocked his inner Goku and performs a devastating KAMEHAMEHAAAA attack causing {0}x extra damage and resulting in an additional {1} damage!.
        /// </summary>
        public static string Kamehameha {
            get {
                return ResourceManager.GetString("Kamehameha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk of murder...holy shit! Player has been hit with a murderous attack ({0}x).
        /// </summary>
        public static string Murder {
            get {
                return ResourceManager.GetString("Murder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk of murder...whew! Just normal damage.
        /// </summary>
        public static string NormalDamage {
            get {
                return ResourceManager.GetString("NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow! Player achieves orgasm, healing {0} points to full health ({1} points)!.
        /// </summary>
        public static string Orgasm {
            get {
                return ResourceManager.GetString("Orgasm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  causing {0} damage, leaving the player with {1} health..
        /// </summary>
        public static string PlayerApocalypseAddendum {
            get {
                return ResourceManager.GetString("PlayerApocalypseAddendum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudden teleportitis (X: {0:0.0}, Y:{1:0.0}, Z:{2:0.0}).
        /// </summary>
        public static string Teleportitis {
            get {
                return ResourceManager.GetString("Teleportitis", resourceCulture);
            }
        }
    }
}
