//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadEcho.Omnified.Vision.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Xaml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Xaml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadEcho.Omnified.Vision.Properties.Xaml", typeof(Xaml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///    &lt;copyright&gt;
        ///        Created by Matt Weber &lt;matt@badecho.com&gt;
        ///        Copyright @ 2022 Bad Echo LLC. All Rights Reserved.
        ///    &lt;/copyright&gt;
        ///--&gt;
        ///&lt;Grid xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;
        ///    
        ///    &lt;ItemsControl ItemsSource=&quot;{Binding Children}&quot; /&gt;
        ///
        ///&lt;/Grid&gt;.
        /// </summary>
        internal static string VisionWindowContent {
            get {
                return ResourceManager.GetString("VisionWindowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///    &lt;copyright&gt;
        ///        Created by Matt Weber &lt;matt@badecho.com&gt;
        ///        Copyright @ 2022 Bad Echo LLC. All Rights Reserved.
        ///    &lt;/copyright&gt;
        ///--&gt;
        ///&lt;Style TargetType=&quot;{x:Type Window}&quot;
        ///           xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///           xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///    &lt;Setter Property=&quot;AllowsTransparency&quot; Value=&quot;True&quot;/&gt;
        ///    &lt;Setter Property=&quot;Background&quot; Value=&quot;Transparent&quot;/&gt;
        ///    &lt;Setter Property=&quot;WindowState&quot; Value=&quot;Maximized&quot;/&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VisionWindowStyle {
            get {
                return ResourceManager.GetString("VisionWindowStyle", resourceCulture);
            }
        }
    }
}
