//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadEcho.Game.Pipeline.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadEcho.Game.Pipeline.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image layer contains no image data..
        /// </summary>
        internal static string ImageLayerNoImage {
            get {
                return ResourceManager.GetString("ImageLayerNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reference to the asset &apos;{0}&apos; was found on this content item..
        /// </summary>
        internal static string NoReferenceInContentItem {
            get {
                return ResourceManager.GetString("NoReferenceInContentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downward direction&apos;s row exceeds the number of rows in the sprite sheet..
        /// </summary>
        internal static string SheetDownwardRowOutOfRange {
            get {
                return ResourceManager.GetString("SheetDownwardRowOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sprite sheet must be configured to have one or more columns in order to be considered valid..
        /// </summary>
        internal static string SheetHasNoColumns {
            get {
                return ResourceManager.GetString("SheetHasNoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sprite sheet must be configured to have one or more rows in order to be considered valid..
        /// </summary>
        internal static string SheetHasNoRows {
            get {
                return ResourceManager.GetString("SheetHasNoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial frame&apos;s row exceeds the number of rows in the sprite sheet..
        /// </summary>
        internal static string SheetInitialRowOutOfRange {
            get {
                return ResourceManager.GetString("SheetInitialRowOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .spritesheet asset identified by {0} consists of a single &apos;null&apos; JSON token, which cannot be processed as sprite sheet. A JSON document conforming to the .spritesheet schema found at http://badecho.com/spritesheet.json must be provided..
        /// </summary>
        internal static string SheetIsNull {
            get {
                return ResourceManager.GetString("SheetIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leftward direction&apos;s row exceeds the number of rows in the sprite sheet..
        /// </summary>
        internal static string SheetLeftwardRowOutOfRange {
            get {
                return ResourceManager.GetString("SheetLeftwardRowOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rightward direction&apos;s row exceeds the number of rows in the sprite sheet..
        /// </summary>
        internal static string SheetRightwardRowOutOfRange {
            get {
                return ResourceManager.GetString("SheetRightwardRowOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upward direction&apos;s row exceeds the number of rows in the sprite sheet..
        /// </summary>
        internal static string SheetUpwardRowOutOfRange {
            get {
                return ResourceManager.GetString("SheetUpwardRowOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile layer contains no tile data..
        /// </summary>
        internal static string TileLayerNoData {
            get {
                return ResourceManager.GetString("TileLayerNoData", resourceCulture);
            }
        }
    }
}
